.TH "CompareCommits.cpp" 3 "Sat May 30 2020" "Version 1.0" "CompareCommits" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompareCommits.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <git2/commit\&.h>\fP
.br
\fC#include <git2/deprecated\&.h>\fP
.br
\fC#include <git2/errors\&.h>\fP
.br
\fC#include <git2/global\&.h>\fP
.br
\fC#include <git2/oid\&.h>\fP
.br
\fC#include <git2/repository\&.h>\fP
.br
\fC#include <git2/revwalk\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'CompareCommits\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CompareCommits from the source code\&.
