.TH "CompareCommits.h" 3 "Sat May 30 2020" "Version 1.0" "CompareCommits" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompareCommits.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'SimilarityMatrix\&.h'\fP
.br
\fC#include 'git2\&.h'\fP
.br
\fC#include <experimental/filesystem>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompareCommits\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOMPARECOMMITS_VERSION\fP   1\&.0"
.br
.RI "Program Version\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMPARECOMMITS_VERSION   1\&.0"

.PP
Program Version\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CompareCommits from the source code\&.
