.TH "SimilarityMatrix.cpp" 3 "Sat May 30 2020" "Version 1.0" "CompareCommits" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimilarityMatrix.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'SimilarityMatrix\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <regex>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBSimilarityMatrix\fP &m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::istream& operator>> (std::istream & is, \fBSimilarityMatrix\fP & m)"
remove leading and trailing whitespace
.SH "Author"
.PP 
Generated automatically by Doxygen for CompareCommits from the source code\&.
