CompareCommits: CompareCommits Class Reference
CompareCommits Class Reference abstract
a class to compare commits and create a NEXUS file representing the distance matrix.
#include <CompareCommits.h>
Public Member Functions
virtual double CompareTwoCommits (std::string commit_path, std::string commit1_path, std::string commit2_path, std::string commit1_filename, std::string commit2_filename, std::string repo_name="")=0
a pure virtual member, calculates the difference between two files.
int CommitCompareAllZip (std::string filename, std::string commit_path)
Compares all zips in given folder, gets two commits and passes to CompareTwoCommits for calculation, adds result to SimilarityMatrix.
int CommitCompareAllGit (std::string filename, std::string repo_name, std::string repo_path, std::string commit_path)
Compares all commits, gets two commits and passes to CompareTwoCommits for calculation, adds result to SimilarityMatrix.
int CommitCompareVector (std::string filename, std::string repo_name, std::string commit_path, std::vector< std::string > &commits)
Compares all commits in vector, gets two commits and passes to CompareTwoCommits for calculation, adds result to SimilarityMatrix.
int CommitCompareStartEnd (std::string filename, std::string repo_name, std::string repo_path, std::string commit_path, std::string start_commit_hash, std::string end_commit_hash)
Gets all commits between start and end commits and adds to vector, passes to CommitCompareVector.
virtual ~CompareCommits ()
a virtual destructor.
Static Public Attributes
static constexpr double VersionNo = COMPARECOMMITS_VERSION
a public variable to store the version number of the class.
Detailed Description
a class to compare commits and create a NEXUS file representing the distance matrix.
Definition at line 35 of file CompareCommits.h.
Member Function Documentation
CommitCompareAllGit()
int CompareCommits::CommitCompareAllGit (std::string filename, std::string repo_name, std::string repo_path, std::string commit_path)
Compares all commits, gets two commits and passes to CompareTwoCommits for calculation, adds result to SimilarityMatrix.
Parameters
filename full path to the directory containing the zipped commits
repo_name name given to repository on GitHub
repo_path full path to repository directory
commit_path full path to commit directory
Returns
0 success or an error code
Definition at line 137 of file CompareCommits.cpp.
References SimilarityMatrix::add(), CompareTwoCommits(), and SimilarityMatrix::NexusOut().
CommitCompareAllZip()
int CompareCommits::CommitCompareAllZip (std::string filename, std::string commit_path)
Compares all zips in given folder, gets two commits and passes to CompareTwoCommits for calculation, adds result to SimilarityMatrix.
Parameters
filename full path to the directory containing the zipped commits
commit_path full path to commit directory
Returns
0 success or an error code
Definition at line 24 of file CompareCommits.cpp.
References SimilarityMatrix::add(), CompareTwoCommits(), and SimilarityMatrix::NexusOut().
CommitCompareStartEnd()
int CompareCommits::CommitCompareStartEnd (std::string filename, std::string repo_name, std::string repo_path, std::string commit_path, std::string start_commit_hash, std::string end_commit_hash)
Gets all commits between start and end commits and adds to vector, passes to CommitCompareVector.
Parameters
filename full path to the directory containing the zipped commits
repo_name name given to repository on GitHub
repo_path full path to repository directory
commit_path full path to commit directory
start_commit_hash the long hash value for the start commit
end_commit_hash the long hash value for the end commit
Returns
0 success or an error code
Definition at line 436 of file CompareCommits.cpp.
References CommitCompareVector().
CommitCompareVector()
int CompareCommits::CommitCompareVector (std::string filename, std::string repo_name, std::string commit_path, std::vector< std::string > & commits)
Compares all commits in vector, gets two commits and passes to CompareTwoCommits for calculation, adds result to SimilarityMatrix.
Parameters
filename full path to the directory containing the zipped commits
repo_name name given to repository on GitHub
commit_path full path to commit directory
commits vector of strings of commits to compare
Returns
0 success or an error code
Definition at line 330 of file CompareCommits.cpp.
References SimilarityMatrix::add(), CompareTwoCommits(), and SimilarityMatrix::NexusOut().
Referenced by CommitCompareStartEnd().
CompareTwoCommits()
virtual double CompareCommits::CompareTwoCommits (std::string commit_path, std::string commit1_path, std::string commit2_path, std::string commit1_filename, std::string commit2_filename, std::string repo_name = "") pure virtual
a pure virtual member, calculates the difference between two files.
Parameters
commit_path full path to the directory containing the files
commit1_path full path to first file
commit2_path full path to second file
commit1_filename the file name of first file
commit2_filename the file name of second file
repo_name repositories name on GitHub
Returns
difference metric between files or an error code
Implemented in DiffCompareCommits.
Referenced by CommitCompareAllGit(), CommitCompareAllZip(), and CommitCompareVector().
The documentation for this class was generated from the following files:
CompareCommits.h
CompareCommits.cpp