CompareCommits: SimilarityMatrix Class Reference
SimilarityMatrix Class Reference
a class representing a similarity or difference matrix using a vector and map.
#include <SimilarityMatrix.h>
Public Member Functions
SimilarityMatrix (size_t size)
Constructor for SimilarityMatrix.
virtual ~SimilarityMatrix ()
Destructor for SimilarityMatrix.
SimilarityMatrix (const SimilarityMatrix &other)
Creates from copied values of other.
SimilarityMatrix & operator= (const SimilarityMatrix &other)
Sets values to those of other.
double & operator() (size_t i, size_t j)
Gets the data at row i, column j.
double operator() (size_t i, size_t j) const
Gets value at row i, column j.
size_t getRows () const
Gets number of rows.
size_t getCols () const
Gets number of columns.
std::vector< double > const & getData () const
Gets reference to vector of similarity data.
HASHINDEX_MAP const & getMap () const
Gets reference to Hash-Index map.
int add (std::string commit1_hash, std::string commit2_hash, double similarity)
Adds similarity between commit1_hash and commit2_hash.
size_t getIndex (std::string commit_hash)
Gets index for commit_hash.
std::string getHash (size_t index)
Gets hash string for value.
int NexusOut (std::string output_path, std::string filename)
Creates NEXUS file at output_path with name 'filename.nxs'.
Protected Attributes
size_t mRows
a protected variable to store number of rows in the matrix.
size_t mCols
a protected variable to store number of columns in the matrix.
std::vector< double > mData
a protected variable to store the data of the matrix.
HASHINDEX_MAP commithashindexmap
a protected variable to store the map of vector index to label.
Detailed Description
a class representing a similarity or difference matrix using a vector and map.
Definition at line 25 of file SimilarityMatrix.h.
Constructor & Destructor Documentation
SimilarityMatrix() [1/2]
SimilarityMatrix::SimilarityMatrix (size_t size)
Constructor for SimilarityMatrix.
Parameters
size
Definition at line 16 of file SimilarityMatrix.cpp.
SimilarityMatrix() [2/2]
SimilarityMatrix::SimilarityMatrix (const SimilarityMatrix & other)
Creates from copied values of other.
Parameters
other constant reference to a SimilarityMatrix object
Definition at line 29 of file SimilarityMatrix.cpp.
Member Function Documentation
add()
int SimilarityMatrix::add (std::string commit1_hash, std::string commit2_hash, double similarity)
Adds similarity between commit1_hash and commit2_hash.
Parameters
commit1_hash
commit2_hash
Returns
0 success or an error code
Definition at line 62 of file SimilarityMatrix.cpp.
References commithashindexmap, getIndex(), mCols, and mData.
Referenced by CompareCommits::CommitCompareAllGit(), CompareCommits::CommitCompareAllZip(), and CompareCommits::CommitCompareVector().
getCols()
size_t SimilarityMatrix::getCols () const inline
Gets number of columns.
Returns
number of columns
Definition at line 155 of file SimilarityMatrix.h.
References mCols.
Referenced by NexusOut().
getData()
std::vector< double > const & SimilarityMatrix::getData () const inline
Gets reference to vector of similarity data.
Returns
constant reference to vector of similarity data
Definition at line 161 of file SimilarityMatrix.h.
References mData.
Referenced by NexusOut().
getHash()
std::string SimilarityMatrix::getHash (size_t index)
Gets hash string for value.
Parameters
value index value for a specific pair in commithashindexmap
Returns
hash string for given value
Definition at line 92 of file SimilarityMatrix.cpp.
References commithashindexmap.
Referenced by NexusOut().
getIndex()
size_t SimilarityMatrix::getIndex (std::string commit_hash)
Gets index for commit_hash.
Parameters
commit_hash key for a pair in commithashindexmap
Returns
Index pointing to start of data for given key, or end() if not found.
Definition at line 86 of file SimilarityMatrix.cpp.
References commithashindexmap.
Referenced by add().
getMap()
HASHINDEX_MAP const & SimilarityMatrix::getMap () const inline
Gets reference to Hash-Index map.
Returns
constant reference to the Hash-Index map
Definition at line 167 of file SimilarityMatrix.h.
References commithashindexmap.
getRows()
size_t SimilarityMatrix::getRows () const inline
Gets number of rows.
Returns
number of rows
Definition at line 149 of file SimilarityMatrix.h.
References mRows.
NexusOut()
int SimilarityMatrix::NexusOut (std::string output_path, std::string filename)
Creates NEXUS file at output_path with name 'filename.nxs'.
Parameters
output_path
filename
Returns
0 success or an error code
Definition at line 114 of file SimilarityMatrix.cpp.
References getCols(), getData(), and getHash().
Referenced by CompareCommits::CommitCompareAllGit(), CompareCommits::CommitCompareAllZip(), and CompareCommits::CommitCompareVector().
operator()() [1/2]
double & SimilarityMatrix::operator() (size_t i, size_t j)
Gets the data at row i, column j.
Parameters
i row
j column
Returns
reference to data at position i,j or an error code
Definition at line 50 of file SimilarityMatrix.cpp.
References mCols, and mData.
operator()() [2/2]
double SimilarityMatrix::operator() (size_t i, size_t j) const
Gets value at row i, column j.
Parameters
i row
j column
Returns
value of data at position i,j or an error code
Definition at line 56 of file SimilarityMatrix.cpp.
References mCols, and mData.
operator=()
SimilarityMatrix & SimilarityMatrix::operator= (const SimilarityMatrix & other)
Sets values to those of other.
Parameters
other constant reference to a SimilarityMatrix object
Returns
reference to SimilarityMatrix
Definition at line 39 of file SimilarityMatrix.cpp.
References commithashindexmap, mCols, mData, and mRows.
The documentation for this class was generated from the following files:
SimilarityMatrix.h
SimilarityMatrix.cpp